### PR TITLE
Claimed paper for Niels & Andreas

### PR DESCRIPTION
**Pull request by cowl**

### CODE REVIEW

**Comment by wouter-swierstra** [comment]
Hi guys, thanks for choosing a paper! I remember reading this paper last year and not being too impressed by it -- if you really want to you can present it, but I'd be happy to advise you about possible alternatives.

**Comment by cowl** [comment]
Hmm, okay - what about the "A natural semantics for lazy evaluation" paper by Launchbury?

**Comment by wouter-swierstra** [comment]
Good choice! I'll add you to the list.

**Comment by cowl** [comment]
Thanks :)

**Pull request closed without merging**
